import React, { useEffect } from "react";

/**
 * Clinical prescription printable view.
 * - Plain black-on-white, document style, no app chrome.
 * - Calls window.print() on mount, then exits back to result on afterprint.
 */
export function PrintView({ result, onExit }) {
  useEffect(() => {
    const handleAfterPrint = () => {
      onExit?.();
    };
    window.addEventListener("afterprint", handleAfterPrint);
    // Slight delay so layout paints before print dialog opens
    const t = setTimeout(() => window.print(), 250);
    return () => {
      clearTimeout(t);
      window.removeEventListener("afterprint", handleAfterPrint);
    };
  }, [onExit]);

  const today = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div data-testid="print-view" className="quill-print-root">
      <div className="quill-print-page">
        <header className="quill-print-header">
          <h1>Clinic Name</h1>
          <p className="quill-print-meta">Date: {today}</p>
        </header>

        <section className="quill-print-section">
          <p>
            <strong>Patient name:</strong> Patient Name
          </p>
        </section>

        <section className="quill-print-section">
          <h2>Prescription</h2>
          <table className="quill-print-table" data-testid="print-medications-table">
            <thead>
              <tr>
                <th>Drug</th>
                <th>Dose</th>
                <th>Frequency</th>
                <th>Instructions</th>
              </tr>
            </thead>
            <tbody>
              {result.suggestions.map((s, i) => {
                const parsed = parseMedication(s.detail);
                return (
                  <tr key={i} data-testid={`print-med-row-${i}`}>
                    <td>{s.label}</td>
                    <td>{parsed.dose}</td>
                    <td>{parsed.frequency}</td>
                    <td>{parsed.instructions}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </section>

        <section className="quill-print-section quill-print-signature">
          <p>Clinician signature: __________</p>
        </section>

        <footer className="quill-print-footer">
          Generated by Quill — suggestions only; valid only with clinician signature.
        </footer>

        <div className="quill-print-screen-actions no-print">
          <button onClick={() => window.print()} className="quill-print-screen-btn">
            Print again
          </button>
          <button onClick={onExit} className="quill-print-screen-btn-secondary">
            Back to record
          </button>
        </div>
      </div>
    </div>
  );
}

/**
 * Lightweight parser for med detail strings like:
 *   "500 mg PO TID for 10 days. Take with food."
 * Falls back gracefully if the shape varies.
 */
function parseMedication(detail) {
  if (!detail) return { dose: "—", frequency: "—", instructions: "—" };

  const sentences = detail.split(".").map((s) => s.trim()).filter(Boolean);
  const head = sentences[0] || "";
  const tail = sentences.slice(1).join(". ").trim();

  // Try to extract dose (e.g. "500 mg", "1 lozenge")
  const doseMatch = head.match(/^([\d./]+\s*(?:mg|g|mcg|ml|tab|tablet|lozenge|capsule|drop|unit)s?\b)/i);
  const dose = doseMatch ? doseMatch[1] : "—";

  // Frequency = remainder of the first sentence after the dose
  let frequency = head;
  if (doseMatch) {
    frequency = head.slice(doseMatch[0].length).trim();
  }
  frequency = frequency || "—";

  const instructions = tail || "—";

  return { dose, frequency, instructions };
}
